### ISSUE TITLE
Uncaught (in promise) DOMException: The play() request was interrupted by a new load request

### ISSUE THREAD

**Issue by qnp** [gruhn/vue-qrcode-reader#68] opened 2018-09-26 13:36 UTC
This error is visible in Chrome console (version 69.0.3497.100)
See https://goo.gl/LdLk22
It should be few simple changes to handle it, maybe only doing:
```
await videoEl.play()
```
L44 of https://github.com/gruhn/vue-qrcode-reader/blob/aebfb044217b3bdb5c12502301442d5d65831e61/src/misc/camera.js
But I did not have time to take a closer look to the codebase.
Thanks for your feebacks.

**Comment by gruhn** [comment] 2018-09-26 20:05
Cool, I didn't know `video.play()` returns a Promise. It looks like Edge doesn't support this though.

In which situation do you see this error? When you change the `camera` prop after the component has been mounted? Or right away?

**Comment by qnp** [comment] 2018-09-26 20:46
I see it right await when the component is mounted (with `{}` passed to prop `camera`).

I don't know if it is a problem to `await` a function that does not return a promise (e.g. if it is not supported), how is it transpiled ? Anyway, we could always do as follows, inspired by the google documentation I previously linked :
```
  const playPromise = video.play();

  if (playPromise !== undefined) {
    try {
      await playPromise;
    } catch (error) {
      // handle problems...
    }
  }

  // the following code
```
Is it relevant ?

**Comment by gruhn** [comment] 2018-10-29 19:39
I think we can close this, [since we're not calling `play()` anymore](https://github.com/gruhn/vue-qrcode-reader/pull/72/files). Feel free to reopen, if this issue persists for some reason.

**Closed by gruhn** 2018-10-29 19:39 UTC

**Comment by branson-simplethread** [comment] 2024-01-19 21:57
I'm seeing an error similar to this in `5.5.1`, on Chrome Version 120.0.6099.216.

"Uncaught (in promise) DOMException: The play() request was interrupted because the media was removed from the document. https://goo.gl/LdLk22"

Looks like `play()` was added back in https://github.com/gruhn/vue-qrcode-reader/commit/fb2af72e92c4e74fcea37c21995199aad9e8f5c9 (`5.3.6`).

**Comment by Sec-ant** [comment] 2024-01-20 01:01
@branson-simplethread We don't `await` the `play()` action but we do [`await` the `loadeddata` event](https://github.com/gruhn/vue-qrcode-reader/blob/master/src%2Fmisc%2Fcamera.ts#L72-L73) after.

Can you provide the steps to reproduce this error?

**Comment by branson-simplethread** [comment] 2024-01-20 17:07
Thanks for responding quickly.

I don't have a minimal test case, but the flow in the app is: the user is presented with the QR code reader (`QrcodeStream`), a text input, and a Continue button. The user can either scan the QR code to automatically fill the input, or fill the input manually, before clicking Continue. Clicking Continue takes the user to another page, where they fill out a form and are then returned to the first page. So in this loop they are given the option to use the QR code reader, but may in fact not and rather proceed regardless of the state of the reader.
