### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by ghost** [gruhn/vue-qrcode-reader#209] opened 2020-11-07 21:48 UTC
**Describe the bug**
Using Nuxt 2.14.6.  In this block of code (dist/VueQrcodeReader.umd.js, version 2.3.14, lines 7924-7937), the try statement fails with `ReferenceError: regeneratorRuntime is not defined`.
```js
try {
  regeneratorRuntime = runtime;
} catch (accidentalStrictMode) {
  // This module should not be running in strict mode, so the above
  // assignment should always work unless something is misconfigured. Just
  // in case runtime.js accidentally runs in strict mode, we can escape
  // strict mode using a global Function call. This could conceivably fail
  // if a Content Security Policy forbids using Function, but in that case
  // the proper solution is to fix the accidental strict mode problem. If
  // you've misconfigured your bundler to force strict mode and applied a
  // CSP to forbid Function, and you're not willing to fix either of those
  // problems, please detail your unique predicament in a GitHub issue.
  Function("r", "regeneratorRuntime = r")(runtime);
}
```
I don't think the module is running in strict mode, since I inserted this snippet from [a stackoverflow answer](https://stackoverflow.com/a/18916788) at the beginning of the `try` block and it logged "non-strict".
```js
var mode = (eval("var __temp = null"), (typeof __temp === "undefined")) ? 
    "strict": 
    "non-strict";
console.log(mode);
```
Note that I can't use the fallback since this website is using a CSP.

**To Reproduce**
I wasn't able to reproduce the error on jsfiddle.  Here's a branch with the error: https://github.com/ccsaposs/qr-codes/tree/scan
And here's a current deployment of that branch: https://deploy-preview-9--qr-codes-e4c760.netlify.app/scan/

To reproduce:
1. Open console
2. Go to sources and click on `/_nuxt/30c199b.modern.js`
3. Pretty-print file
4. Set breakpoint at line 9901 (`Function("r", "regeneratorRuntime = r")(n)`)
5. Log `t` to get the error

**Desktop (please complete the following information):**
 - OS: ChromeOS
 - Browser: Chrome
 - Version: 86

**Comment by ccsaposs** [comment] 2020-11-10 21:58
I added 'unsafe-eval' to my CSP as a temporary, unmerged fix in order to keep developing, and I ran into more CSP issues--this time with style.

Here's a branch: https://github.com/ccsaposs/qr-codes/tree/scan-eval
Here's a deployment of that branch: https://deploy-preview-16--qr-codes-e4c760.netlify.app/

Here are the errors:
![Screenshot 2020-11-10 at 1 49 29 PM](https://user-images.githubusercontent.com/32380359/98737906-c5a73d80-235b-11eb-84d3-db54640b6e73.png)
![Screenshot 2020-11-10 at 1 49 12 PM](https://user-images.githubusercontent.com/32380359/98737907-c63fd400-235b-11eb-9f0c-f479ab16bf36.png)
![Screenshot 2020-11-10 at 1 48 59 PM](https://user-images.githubusercontent.com/32380359/98737908-c6d86a80-235b-11eb-8d3c-9f0293fd0cf5.png)

Looking at the source, it looks like `createStyleElement()` and `applyToTag()` are the two errors (called in lines 5186-5187 of dist/VueQrcodeReader.umd.js, version 2.3.14).  I think the issue is that it's trying to apply styles on the client that weren't present during Nuxt static generation.  (Our build is set up to automatically add the hashes for inline styles that are present during static generation.)

Is there a fix for this?

**Comment by gruhn** [comment] 2020-11-12 18:54
@ccsaposs thanks for being so elaborate. This sounds like a complex issue. Forgive me if I can't find the time to deal with this as soon as possible.

**Comment by ccsaposs** [comment] 2020-12-05 17:53
@gruhn I was looking into this more, and I was wondering: is it possible to import `vue-qrcode-reader` without putting it in strict mode?

**Closed** 2023-08-10 00:15 UTC
Labels: no-issue-activity
