### ISSUE TITLE
Detect and tracking don't work anymore if choose a camera with constraints

### ISSUE THREAD

**Issue by viac92** [gruhn/vue-qrcode-reader#416] opened 2024-02-05 10:48 UTC
Hi everyone,

When I use the qrcodestream component like this everything works well.

```html
<qrcode-stream
      :formats="selectedBarcodeTypes"
      :track="selected.value"
      @detect="onDetect"
      @error="logErrors"
/>
```

but when I select a specific camera with the constraints I can switch camera but all the logic doesn't work anymore

```html
 <p>
  <select v-model="selectedDevice">
    <option
      v-for="device in devices"
      :key="device.label"
      :value="device"
    >
      {{ device.label }}
    </option>
  </select>
</p>

<qrcode-stream
      :constraints="{ deviceId: selectedDevice.deviceId }"
      :formats="selectedBarcodeTypes"
      :track="selected.value"
      @detect="onDetect"
      @error="logErrors"
      v-if="selectedDevice !== null"
  />
<p v-else>
    No camera available
</p>
```

in script setup I get the devices like this: 

```js
const selectedDevice = ref(null)
const devices = ref([])

onMounted(async () => {
  await navigator.mediaDevices.getUserMedia({video: true});
  devices.value = (await navigator.mediaDevices.enumerateDevices()).filter(
    ({ kind }) => kind === 'videoinput'
  )

  if (devices.value.length > 0) {
    selectedDevice.value = devices.value[0]
  }
})
```

I add `await navigator.mediaDevices.getUserMedia({video: true});` bc without it I don't get the devices on safari.

**Comment by gruhn** [comment] 2024-02-07 22:49
Thanks, I'm not sure if I reproduced your problem exactly but I found a bug and merged a fix. Please install [v5.5.2](https://github.com/gruhn/vue-qrcode-reader/releases/tag/v5.5.2) and check if you can still reproduce your problem. 

As for the Safari issue you mention:
> I add await navigator.mediaDevices.getUserMedia({video: true}); bc without it I don't get the devices on safari.
I'm not sure what's going on there.

**Comment by marcelloromanelli** [comment] 2024-02-14 14:40
@viac92 I have the same issue. I've downgraded to `5.3.0` and it seems to be working ok there.
In my case if I specify the constraints onDetect is not being called

**Comment by gruhn** [comment] 2024-02-15 15:33
@marcelloromanelli I can't reproduce this issue. Can you provide a minimal reproduction? Ideally somewhere online.

**Comment by gruhn** [comment] 2024-02-26 19:02
Yeah, there is a lot of async stuff going. I suspect there are some race conditions.

**Comment by superboyso** [comment] 2024-03-07 06:58
> Yeah, there is a lot of async stuff going. I suspect there are some race conditions.

please fix it

**Comment by gruhn** [comment] 2024-03-07 07:20
Please provide a way for me to reproduce it

**Closed** 2024-05-14 00:14 UTC
Labels: no-issue-activity
