### ISSUE TITLE
Scanner does not work if we scan after 20s on iPhone 

### ISSUE THREAD

**Issue by nitin282001** [gruhn/vue-qrcode-reader#220] opened 2021-01-11 16:50 UTC
I am using this library in my WordPress site along with Gravity forms, I have one issue after opening the scanner if we have not scan the qr for like 20 or 30sec and after that we scan the qr it does not scan.
Can anyone tell me why ? if anyone knows then please help me out of it. @gruhn  :)
Thanks in advance :)

**Comment by gruhn** [comment] 2021-01-11 21:44
Sounds like duplicate of #207

**Closed** 2021-01-14 11:51 UTC
