### ISSUE TITLE
Choose file

### ISSUE THREAD

**Issue by dakshshah96** [gruhn/vue-qrcode-reader#63] opened 2018-09-11 18:13 UTC
Thank you for this library and your continued support 🎉 

On devices where `navigator.getUserMedia` is not supported such as non-Safari browsers and installed PWAs on iOS, I want to fallback to giving users the option to upload a picture of the QR code.

I've gotten drag-and-drop to work properly but for mobile devices drag-and-drop wouldn't make sense so how do I display a 'Choose file' button and decode a QR code from the uploaded image using this library?

**Comment by gruhn** [comment] 2018-09-11 20:09
Duplicate of #56

**Closed** 2018-10-29 19:04 UTC
Labels: duplicate
